buildscript {
    ext.kotlin_version = '1.9.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.15'
        // END: FlutterFire Configuration
        // classpath 'com.android.tools.build:gradle:7.6.2'
        classpath "com.android.tools.build:gradle:8.9.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}


allprojects {
    repositories {
        google()
        mavenCentral()
    }

  //   configurations.all {
  //   resolutionStrategy {
  //     // Ép tất cả các module (kể cả flutter_health_connect) dùng version 1.1.0-rc01
  //     force "androidx.health.connect:connect-client:1.1.0-rc01"
  //   }
  // }



    subprojects {
    afterEvaluate { proj ->
    if (proj.plugins.hasPlugin("com.android.library")) {
      proj.android {
        if (namespace == null || namespace.isEmpty()) {
          namespace = proj.group?.toString() ?: "com.example.${proj.name}"
        }
      }
    }
  }
}

    // configurations.all {
    //     exclude group: 'com.google.errorprone', module: 'error_prone_annotations'
    // }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
