// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9-Qc7vQqVIrCfSXahAbznYlo4qxew-M0',
    appId: '1:655372762225:web:b2ea5e0531541ede36efd0',
    messagingSenderId: '655372762225',
    projectId: 'fitness-594a2',
    authDomain: 'fitness-594a2.firebaseapp.com',
    storageBucket: 'fitness-594a2.firebasestorage.app',
    measurementId: 'G-6NB0MR3R6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUarmv_FyJ8nOqKFNNgIqWOrCaPQMkCsI',
    appId: '1:655372762225:android:f3ccc912191bdb9636efd0',
    messagingSenderId: '655372762225',
    projectId: 'fitness-594a2',
    storageBucket: 'fitness-594a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJKwjf8QNrEou5MxW8kOcaF8-clpGJLrg',
    appId: '1:655372762225:ios:dd9c7d4a63ab64a036efd0',
    messagingSenderId: '655372762225',
    projectId: 'fitness-594a2',
    storageBucket: 'fitness-594a2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJKwjf8QNrEou5MxW8kOcaF8-clpGJLrg',
    appId: '1:655372762225:ios:dd9c7d4a63ab64a036efd0',
    messagingSenderId: '655372762225',
    projectId: 'fitness-594a2',
    storageBucket: 'fitness-594a2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9-Qc7vQqVIrCfSXahAbznYlo4qxew-M0',
    appId: '1:655372762225:web:5123b24cf084371436efd0',
    messagingSenderId: '655372762225',
    projectId: 'fitness-594a2',
    authDomain: 'fitness-594a2.firebaseapp.com',
    storageBucket: 'fitness-594a2.firebasestorage.app',
    measurementId: 'G-END89V0JHS',
  );
}
